### ISSUE TITLE
Roadmap overview

### ISSUE THREAD

**Issue by ruv** [ForthHub/fep-recognizer#1]
[under construction]

- [ ] [General requirements and principles](./18)
- [ ] [Terms definitions and data types](./2)
- [ ] [The minimal essential part](./13)
- Important choices
  - [ ] [Side effects of recognizers](./7)
  - [ ] [Defer is unsuitable](./5)
  - [ ] [Unrecognized vs zero](./4)
- [ ] [Naming](./3)
- [ ] Glossary
- [ ] Glossary extension

### References

- [Forth Recognizer](https://forth-standard.org/proposals/recognizer#reply-897) (retired)
- [Recognizer RfD rephrase 2020](https://forth-standard.org/proposals/recognizer-rfd-rephrase-2020#reply-898) (retired)
- [Comparison of terminology in different proposals](https://gist.github.com/ruv/af796cece2ecd2ee541d883a04483dcc#file-11-comparision-to-some-past-versions-md)
- [minimalistic core API for recognizers](https://forth-standard.org/proposals/minimalistic-core-api-for-recognizers#reply-1081)
